name: Update PR labels

on:
  pull_request:
    types: [closed]

jobs:
  after-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: cachix/install-nix-action@v30

      - run: nix-env -iA nixpkgs.github-cli

      - name: Update labels on accepted RFCs
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          # Only operate on PR if it has the `status: accepted` label
          if gh pr view $PR_NUMBER --repo $REPO --json labels -q 'any(.[].name == "status: accepted")'; then
            gh pr edit $PR_NUMBER --remove-label "status: accepted" --repo $REPO
            gh pr edit $PR_NUMBER --add-label "status: merged" --repo $REPO
          fi
